import { Budget } from "@/lib/network/types";

export const mockBudgets: Budget[] = [
    {
        id: "1",
        name: "June 2024 Budget",
        totalAmount: 5000,
        amountSpent: 4285.5,
        startDate: "2024-06-01",
        endDate: "2024-06-30",
        currency: "EUR",
        usedPercentage: 85.71,
        remainingPercentage: 14.29,
        allocations: [
            {
                id: "1",
                category: "Food",
                allocatedAmount: 1500,
                amountSpent: 1200,
            },
            {
                id: "2",
                category: "Transport",
                allocatedAmount: 800,
                amountSpent: 600,
            },
            {
                id: "3",
                category: "Entertainment",
                allocatedAmount: 700,
                amountSpent: 500,
            },
            {
                id: "4",
                category: "Food",
                allocatedAmount: 1500,
                amountSpent: 1200,
            },
        ],
    },
    {
        id: "2",
        name: "July 2024 Budget",
        totalAmount: 4500,
        amountSpent: 3200,
        startDate: "2024-07-01",
        endDate: "2024-07-31",
        currency: "EUR",
        usedPercentage: 71.11,
        remainingPercentage: 28.89,
        allocations: [
            {
                id: "1",
                category: "Food",
                allocatedAmount: 1200,
                amountSpent: 0,
            },
            {
                id: "2",
                category: "Transport",
                allocatedAmount: 600,
                amountSpent: 0,
            },
            {
                id: "3",
                category: "Entertainment",
                allocatedAmount: 500,
                amountSpent: 0,
            },
            {
                id: "4",
                category: "Food",
                allocatedAmount: 1200,
                amountSpent: 0,
            },
        ],
    },
    {
        id: "3",
        name: "August 2024 Budget",
        totalAmount: 4800,
        amountSpent: 1200,
        startDate: "2024-08-01",
        endDate: "2024-08-31",
        currency: "NGN",
        usedPercentage: 25,
        remainingPercentage: 75,
        allocations: [
            {
                id: "1",
                category: "Food",
                allocatedAmount: 1300,
                amountSpent: 0,
            },
            {
                id: "2",
                category: "Transport",
                allocatedAmount: 700,
                amountSpent: 0,
            },
            {
                id: "3",
                category: "Entertainment",
                allocatedAmount: 500,
                amountSpent: 0,
            },
        ],
    },
    {
        id: "4",
        name: "August 2024 Budget",
        totalAmount: 4800,
        amountSpent: 800,
        startDate: "2024-08-01",
        endDate: "2024-08-31",
        currency: "GBP",
        usedPercentage: 16.67,
        remainingPercentage: 83.33,
        allocations: [
            {
                id: "1",
                category: "Food",
                allocatedAmount: 1300,
                amountSpent: 0,
            },
            {
                id: "2",
                category: "Transport",
                allocatedAmount: 700,
                amountSpent: 0,
            },
        ],
    },
    {
        id: "5",
        name: "July 2024 Budget",
        totalAmount: 4500,
        amountSpent: 4800,
        startDate: "2024-07-01",
        endDate: "2024-07-31",
        currency: "USD",
        usedPercentage: 106.67,
        remainingPercentage: -6.67,
        allocations: [
            {
                id: "1",
                category: "Food",
                allocatedAmount: 1200,
                amountSpent: 0,
            },
            {
                id: "2",
                category: "Transport",
                allocatedAmount: 600,
                amountSpent: 0,
            },
            {
                id: "3",
                category: "Entertainment",
                allocatedAmount: 500,
                amountSpent: 0,
            },
        ],
    },
];
