import { Expense } from "@/lib/network/types";

export const mockExpenses: Expense[] = [
    {
        id: "1",
        name: "Grocery Shopping",
        amount: 120.5,
        category: "Food",
        currency: "USD",
        date: "2024-06-01",
    },
    {
        id: "2",
        name: "Electricity Bill",
        amount: 60.75,
        category: "Utilities",
        currency: "USD",
        date: "2024-06-03",
    },
    {
        id: "3",
        name: "Dinner at Restaurant",
        amount: 45.0,
        category: "Food",
        currency: "USD",
        date: "2024-06-05",
    },
    {
        id: "4",
        name: "Monthly Subscription",
        amount: 15.99,
        category: "Entertainment",
        currency: "USD",
        date: "2024-06-07",
    },
    {
        id: "5",
        name: "Gas Refill",
        amount: 30.0,
        category: "Rent",
        currency: "NGN",
        date: "2024-06-10",
    },
    {
        id: "6",
        name: "Movie Tickets",
        amount: 25.0,
        category: "Entertainment",
        currency: "EUR",
        date: "2024-06-12",
    },
    {
        id: "7",
        name: "Coffee",
        amount: 4.5,
        category: "Food",
        currency: "EUR",
        date: "2024-06-15",
    },
    {
        id: "8",
        name: "Gym Membership",
        amount: 50.0,
        category: "Health",
        currency: "EUR",
        date: "2024-06-18",
    },
    {
        id: "9",
        name: "Online Course",
        amount: 100.0,
        category: "Other",
        currency: "EUR",
        date: "2024-06-20",
    },
    {
        id: "10",
        name: "Car Maintenance",
        amount: 200.0,
        category: "Utilities",
        currency: "EUR",
        date: "2024-06-25",
    },
];
